In [1]:
import numpy as np

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
a

NameError: name 'a' is not defined

In [4]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
typr(ar)

NameError: name 'typr' is not defined

In [6]:
type(ar)

numpy.ndarray

In [9]:
for i in range(ar):
    println(i)


TypeError: only integer scalar arrays can be converted to a scalar index

In [10]:
ar.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
ab = [1,2,3]

In [12]:
ab

[1, 2, 3]

In [13]:
ab.append(4)

In [14]:
ab

[1, 2, 3, 4]

In [15]:
ab.delete(3)

AttributeError: 'list' object has no attribute 'delete'

In [16]:
ar * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
ab *2

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
cc= np.array([5,6,7])

In [19]:
ar + cc

ValueError: operands could not be broadcast together with shapes (10,) (3,) 

In [20]:
ar + ab

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [21]:
cc = ar+ab

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [22]:
cc = ar+cc

ValueError: operands could not be broadcast together with shapes (10,) (3,) 

In [23]:
ar + cc

ValueError: operands could not be broadcast together with shapes (10,) (3,) 

In [24]:
clear

In [27]:
dd = np.array([[1,2,3],[4,5,6]])

In [28]:
dd

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
dd.dtype   #data type

dtype('int64')

In [31]:
aaa = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [32]:
aaa.shape

(2, 3, 3)

In [33]:
aaa

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
aaa.ndim #차원 알아내기

3

In [35]:
type(aaa)

numpy.ndarray

In [36]:
aaa.dtype

dtype('int64')

In [37]:
aaa.shape

(2, 3, 3)

In [38]:
aaa.ndim

3

In [40]:
len(aaa)

2

In [42]:
aaa[0,1,0] # aaa[0][1][0]

4

In [43]:
a = np.array([[1,2,3],[4,5,6]])

In [44]:
b = np.array([1,2,4,5,6])

In [45]:
b[0:2]

array([1, 2])

In [46]:
b[2:]

array([4, 5, 6])

In [47]:
a = np.array([[1,2,3],[4,5,6]])

In [49]:
a[0,0:2] # 0번째 인덱스의 0:2

array([1, 2])

In [52]:
for i in range(1,10,2) :
    print(i)

1
3
5
7
9


In [85]:
a= np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [64]:
for i in range(2,4):
        print(a[i])
    

3
4
8
9


In [65]:
b = np.array([1,2,3,4])

In [66]:
b

array([1, 2, 3, 4])

In [67]:
b.shape

(4,)

In [68]:
b=np.array([[],[]])

In [86]:
b = a[0:2,2:4]

In [70]:
b

array([[3, 4],
       [8, 9]])

AttributeError: 'numpy.ndarray' object has no attribute 'nbim'

In [80]:
a = range(2,4)

In [73]:
a.ndim

2

In [74]:
b.ndim

2

In [88]:
for i in range(2,4):
    print(a[0,i-1])

2
3


In [90]:
for j in range(2):
    for i in range(2,4):
        print(a[j,i])

3
4
8
9


In [92]:
b = np.array([[],[]])

In [93]:
b = a[0:2,1:3]

In [94]:
b

array([[2, 3],
       [7, 8]])

In [96]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [104]:
for j in range(2):
    for i in range(2):
        sum = sum + a[j,i]

TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'int'

In [105]:
np.sum(a)

45

In [108]:
a = np.array([0,1,0,0])

In [109]:
b = np.array([1,1,0,0])

In [110]:
c = a*b   # 같은 차원끼리 곱함

In [111]:
c

array([0, 1, 0, 0])

In [112]:
np.sum(c)

1

In [113]:
block_L = np.array([[0,1,0,0],[1,0,0,0]])

In [114]:
block_L.ndim

2

In [115]:
block_L.shape

(2, 4)

In [116]:
block_L.dtype

dtype('int64')

In [117]:
block_L = np.array([[0,0,0,0],
                   [0,1,0,0],
                   [0,1,1,1],
                   [0,0,0,0]])

In [118]:
background = np.array([[0,1,0,0],
                      [0,1,1,1],
                      [0,0,0,0],
                      [0,0,0,0]])

In [119]:
background.shape

(4, 4)

In [120]:
c = block_L * background

In [121]:
c

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])